spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: weiiibj8079727
  thymeleaf:
    mode: HTML
    prefix: classpath:/static/
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


mybatis:
  type-aliases-package: com.house.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

